# Constitution

This document establishes the governing framework for the Greater Peninsula Swimming Association.

## Name

1. The name of this organization shall be GREATER PENINSULA SWIMMING ASSOCIATION.

2. This organization will use the name or its acronym, GPSA, in all publicity materials and correspondence.

## Objectives

1. The purpose of the Association is to promote swimming on the Peninsula.

## Fiscal Year

1. The fiscal year of the Association shall begin on September 1st and end August 31st.

## Membership

The membership of the Association shall be teams and members thereof:

1. Team membership shall consist of organized local swim teams or clubs.

    a. All applications for membership must be submitted in writing to the Secretary of the Association and endorsed by three members of the GPSA Board of Directors

    b. The Secretary shall present all applications to the Board of Directors.

    c. New membership requires a two-thirds vote of the Board of Directors.

    d. The Board of Directors may, at its discretion, limit the membership.

    e. Two or more teams representing the same pool may hold membership in GPSA. Each team shall be treated as a totally separate entity with one exception. Notwithstanding any other provisions in the Constitution or Rules for Interpool Meets, under NO CIRCUMSTANCES will a swimmer be allowed to move from one team roster to another from the same pool once his or her name is submitted in accordance with the provisions of the eligibility requirements of the Rules for Interpool Meets.

    f. One team representing two or more pools may hold membership in the GPSA. The pools will adopt one name and shall be treated as one entity. The guidelines for new membership listed herein apply to both new pools and pools that are already members of the GPSA and desire to form one club.

    g. Teams may be removed from GPSA by a two-thirds vote of the entire Board of Directors.

2. The GPSA membership may be divided into divisions for the purpose of establishing schedules for regular season competition.

    a. After the end of each swimming season, the President shall appoint an Alignment and Schedule Committee to review the previous season's results. Based on this review, the committee shall present for the board's approval at its November meeting any adjustments in alignment deemed necessary. The alignment consideration shall include any new team(s) accepted into the association.

    b. Based on the approved alignment, the Alignment and Schedule Committee shall prepare and present for the Board's approval at its March meeting a schedule for official competition during the forthcoming season. This schedule shall include as a minimum:

        i. At least one dual meet for each team against all other teams within its division.

        ii. A Summer Splash Invitational open to all GPSA swimmers not meeting qualifying times for the Championship Meet.

        iii. A season-ending Championship Meet open to all GPSA swimmers meeting qualifying times.

## Board of Directors

1. Each member club shall elect one member to represent them on the Board of Directors for the term of one year starting in September.

2. The Members-at-Large shall consist of a minimum of three and a maximum of seven to serve on the Board of Directors. The Members-at-Large shall preferably be from different clubs. In no case shall more than two Members-at-Large be from one member club. The Members-at-Large shall be elected at the annual meeting (held in November) and starting to serve in December. Additional Members-at-Large may be elected at any time the total number of Members-at-Large is less than seven to serve until the next annual meeting.

## Meetings

1. The annual meeting shall be held in November when committee reports shall be given and up to seven Members-at-Large shall be elected.

2. The Board of Directors shall hold meetings in September, November (annual), January, March and May, or as needed to accomplish the business of the Association. The Date and time shall be set for the next meeting before adjourning the present meeting.

3. Members of the Board of Directors shall attend all meetings or have a voting substitute, failure to have representation for two consecutive meetings may be grounds for requesting a replacement.

4. A quorum for a Board Meeting shall be seven members of the Board of Directors.

5. Any three Directors may petition the President of GPSA for a called Board Meeting. The President must then call the meeting within two weeks after the receipt of the petition.

## Dues

1. Dues shall be established by the Board of Directors.

2. The Treasurer shall present a statement to each club representative by mid-July.

3. Dues for the fiscal year shall be due at the Championship Meet.

4. Any member whose dues are more than forty-five days in arrears may be dropped from membership at the discretion of the Board of Directors.

## Organization

1. The officers of GPSA shall be President, Vice-President, Secretary and Treasurer.

2. All officers of GPSA shall be active members of the Board of Directors of GPSA.

3. The term of office shall be one year and all shall be eligible for reelection.

4. Committees - The President shall appoint any committee necessary for the operation of the Association in addition to:

    a. Rules Committee - of three plus two alternates appointed by the President shall handle protests and keep GPSA Rules current with United States Swimming, when practical

    b. Publicity Committee - to organize public relations of the Association and assist members in this activity by cooperating with all media.

    c. Championship Meet Chairman - To arrange an annual Championship Meet for participation by qualified swimmers belonging to GPSA (closed meet).

    d. Nominating Committee - of three members of the Board of Directors appointed by the President in September and to report to the November Board Meeting.

    e. Alignment and Schedule Committee - of a chairman and a minimum of at least one member from each division appointed by the President to recommend alignment changes and to work up a meet schedule for summer competition.

    f. Other than the Nominating Committee, the President has the option to appoint as committee members those who are not members of the Board of Directors.

## Amendments

1. This Constitution may be amended by a two-thirds vote of the Board of Directors attending the Annual Meeting or a called meeting for that purpose. All amendments must have been sent to the GPSA Representatives at least ten days in advance of the meeting.
