# Code of Conduct

The purpose of this Code is to promote the best possible association, team and individual impression at all times, and to acknowledge each swimmer's responsibilities as members of our association. It is the responsibility of the GPSA Representative to ensure that all swimmers, parents, and coaches are knowledgeable of this Code of Conduct and abide by it.

## Part I - General Conduct

1. All participating GPSA swimmers shall abide by this Code of Conduct.

2. The use of drugs other than those prescribed by a physician or over the counter drugs is forbidden.

3. Vandalism or pranks against other teams will not be tolerated.

4. Poor sportsmanship of any kind will not be tolerated.

5. Swimmers will treat their membership on a GPSA team as a privilege and personally acknowledge those associated responsibilities.

## Part II - Coaches' Conduct

1. All GPSA coaches shall abide by this Code of Conduct.

2. Supplying alcoholic beverages, tobacco products, or drugs to swimmers is forbidden.

3. Engaging in, or encouraging swimmers to engage in, vandalism or pranks against other teams will not be tolerated.

4. Poor sportsmanship of any kind will not be tolerated.

5. Coaches will acknowledge that their employment by a GPSA team is a privilege and personally acknowledge those associated responsibilities.

## Part III - Parent or Guardian Conduct

1. All Parents or Guardians of GPSA swimmers shall abide by this Code of Conduct.

2. Supplying alcoholic beverages, tobacco products, or drugs to swimmers is forbidden.

3. Engaging in, or encouraging swimmers to engage in, vandalism or pranks against other teams will not be tolerated.

4. Poor sportsmanship of any kind will not be tolerated.

5. Parents or Guardians of GPSA swimmers shall acknowledge that their participation in GPSA sanctioned events is a privilege and personally acknowledge their responsibilities of setting the example of this Code of Conduct.

## Part IV - Violation of the Code of Conduct

1. Observed or alleged violation of this Code of Conduct during meets will be reported to the Referee for disposition in accordance with GPSA rules.

2. Observed or alleged violations of the Code of Conduct outside of meets will be referred to the GPSA Rules Committee for disposition. The GPSA Representatives for the teams in question will appear before the GPSA Rules Committee to present the facts associated with the alleged violation. The Rules Committee will present their findings to the GPSA Board of Directors.

3. Depending on the vote of the Board, a team's/individual's punishment may involve sanctions up to, and including, removal from GPSA.

## Part V - Right to Appeal

1. The decision of the GPSA Board of Directors is final. The right to appeal will only be granted in the event new evidence comes to light.
